[package]
name = "jam-sesh-server"
version = "0.1.0"
authors = ["Luis G. Torres <lgtorres42@gmail.com>"]

[dependencies]
websocket = "0.20.2"
serde = "1.0.36"
serde_derive = "1.0.36"
serde_json = "1.0.13"
