[package]
name = "jam-sesh-server"
version = "0.1.0"
authors = ["Luis G. Torres <lgtorres42@gmail.com>"]
edition = "2021"

[dependencies]
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
websocket = "0.26.3"
